spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
  hikari:
    jdbc-url: jdbc:h2:mem

